"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add', 'subtract']

# %% ../nbs/00_core.ipynb 3
def add(a, b):
    """Adds two numbers together."""
    return a + b

def subtract(a, b):
    """
    Subtracts two numbers.
    
    :param a: The first number
    :param b: The second number
    """

    return a - b
