"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add', 'subtract']

# %% ../nbs/00_core.ipynb 3
def add(a: float, # First number
        b: float # Second number
        )->float: # The sum
    """Adds two numbers together."""
    return a + b

def subtract(a: float, # First number
             b: float # Second number
             )->float: # The difference
    """Subtracts two numbers."""
    return a - b
