"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add']

# %% ../nbs/00_core.ipynb 3
def add(a, b):
    """Adds two numbers together."""
    return a + b
