"""Function to say hello to a specific person"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_hello_sayer.ipynb.

# %% auto 0
__all__ = ['hello_sayer']

# %% ../nbs/01_hello_sayer.ipynb 3
print("Start the hello sayer...")
def hello_sayer(name:str # Name of the person
                )->str: # The greeting
    return f"Hello {name}"
